"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let number = 5;
console.log("Is number == 5? I predict True.");
console.log(number == 5);
let name = "Hammad";
console.log("Is name == 'Hammad'? I predict True.");
console.log(name == 'Hammad');
let isSunny = true;
console.log("Is it sunny? I predict True.");
console.log(isSunny);
let age = 21;
console.log("Is age >= 21? I predict True.");
console.log(age >= 21);
let fruit = 'banana';
console.log("Is fruit == 'banana'? I predict true.");
console.log(fruit == 'banana');
let temperature = 30;
console.log("Is temperature < 0? I predict False.");
console.log(temperature < 0);
let isWeekend = false;
console.log("Is it the weekend? I predict False.");
console.log(isWeekend);
let timeOfDay = 'morning';
console.log("Is timeOfDay == 'evening'? I predict False.");
console.log(timeOfDay == 'evening');
let hasPermission = false;
console.log("Does the user have permission? I predict false.");
console.log(hasPermission);
let favoriteColor = 'blue';
console.log("Is favoriteColor == 'green'? I predict False.");
console.log(favoriteColor == 'green');
